apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: desafio
type: Opaque
stringData:
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: "senha_exemplo"
  PGRST_DB_URI: postgres://postgres:postgres@database:5432/desafio